name: CI (плохой)

on:
  push:
  pull_request:
  schedule:
    - cron: "0 * * * *"

permissions: write-all

jobs:
  all-in-one:
    runs-on: ubuntu-latest

    steps:
      - name: чекаут
        uses: actions/checkout@v4

      - name: установка Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: установка зависимостей
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt

      - name: все в одном шаге
        continue-on-error: true
        run: |
          ruff --version
          ruff check .
          python -m pytest -q
